services:
  - type: web
    name: recommendationmovies
    runtime: docker
    dockerfilePath: ./Dockerfile
    region: singapore
    plan: free
    branch: main
    rootDir: .
    envVars:
      - key: PORT
        value: 5000
      - key: CORS_ORIGIN
        value: "*"
      - key: PYTHON_PATH
        value: /usr/bin/python3.10
      - key: TMDB_API_KEY
        value: 089e206e52ab82845bf53efa520c2bf5
      - key: MONGO_URI
        value: mongodb+srv://kaosks123:9twPZGXzg4k3Yik1@capstonemovie.kkqwq.mongodb.net/?retryWrites=true&w=majority&appName=capstoneMovie